=== romkuz01/mbed-os-example-uvisor-thread/manifests/partition_description.dtd
<!ELEMENT partition (code, stack, heap, mmio?, sfid*, src+, irq_num*, extern_sfid*,
    spm_status?, context_structure_name, global_heap?)>
<!ATTLIST partition name CDATA #REQUIRED>
<!ATTLIST partition priority CDATA #REQUIRED>

<!-- Code section definition -->
<!ELEMENT code EMPTY>
<!ATTLIST code entry_point CDATA #REQUIRED>

<!-- Stack size definition -->
<!ELEMENT stack EMPTY>
<!ATTLIST stack size CDATA #REQUIRED>

<!-- Heap size definition -->
<!ELEMENT heap EMPTY>
<!ATTLIST heap size CDATA #REQUIRED>

<!-- MMIO regions -->
<!ELEMENT mmio (mmioregion_named*, mmioregion*)>
<!ELEMENT mmioregion_named EMPTY>
<!ATTLIST mmioregion_named base CDATA #REQUIRED>
<!ATTLIST mmioregion_named permissions CDATA #REQUIRED>
<!ELEMENT mmioregion EMPTY>
<!ATTLIST mmioregion base CDATA #REQUIRED>
<!ATTLIST mmioregion size CDATA #REQUIRED>
<!ATTLIST mmioregion permissions CDATA #REQUIRED>

<!-- Declaration of SFIDs -->
<!ELEMENT sfid (#PCDATA)>

<!-- Source files -->
<!ELEMENT src (filename+)>
<!ELEMENT filename (#PCDATA)>

<!-- Reserved IRQ numbers -->
<!ELEMENT irq_num (#PCDATA)>

<!-- SFID dependencies -->
<!ELEMENT extern_sfid (#PCDATA)>

<!--uVisor extensions -->
<!ELEMENT spm_status (#PCDATA)>

<!ELEMENT context_structure_name (#PCDATA)>

<!ELEMENT global_heap EMPTY>
<!ATTLIST global_heap page_size CDATA #REQUIRED>
<!ATTLIST global_heap minimal_page_number CDATA #REQUIRED>

=== romkuz01/mbed-os-example-uvisor-thread/manifests/box_main.xml
<!DOCTYPE partition SYSTEM "partition_description.dtd">
<partition name = "box_main" priority = "osPriorityNormal">

<code entry_point = "main"/>

<stack size = "512"/>

<heap size = "2048"/>

<mmio>
<mmioregion_named base = "CMU" permissions = "UVISOR_TACLDEF_PERIPH"/>
<mmioregion_named base = "MSC" permissions = "UVISOR_TACLDEF_PERIPH"/>
<mmioregion_named base = "GPIO" permissions = "UVISOR_TACLDEF_PERIPH"/>
<mmioregion_named base = "TIMER0" permissions = "UVISOR_TACLDEF_PERIPH"/>
<mmioregion_named base = "UART0" permissions = "UVISOR_TACLDEF_PERIPH"/>
<mmioregion base = "0x0FE08000" size = "0x1000" permissions = "UVISOR_TACLDEF_PERIPH"/>
<mmioregion base = "0x42000000" size = "0x2000000" permissions = "UVISOR_TACLDEF_PERIPH"/>
</mmio>

<src>
<filename>../source/main.cpp</filename>
</src>

<!-- uVisor extensions -->
<spm_status>UVISOR_ENABLED</spm_status>
<context_structure_name>box_context</context_structure_name>
<global_heap page_size = "2048" minimal_page_number = "8"/>

</partition>

=== romkuz01/mbed-os-example-uvisor-thread/manifests/box_led1.xml
<!DOCTYPE partition SYSTEM "partition_description.dtd">
<partition name = "box_led1" priority = "osPriorityNormal">

<code entry_point = "led1_main"/>

<stack size = "512"/>

<heap size = "2048"/>

<src>
<filename>../source/led1.cpp</filename>
</src>

<!-- uVisor extensions -->
<context_structure_name>box_context</context_structure_name>

<global_heap page_size = "0x1000" minimal_page_number = "8"/>

</partition>
